### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by savan8192** [Richard-Gemmell/lsm9ds1-rjg#1]
Hi Richard,

Thanks for the library. It would be really helpful if you can add some notes on how to use this. 

I have a lsm9ds1 connected, just wanted to run your examples to test whether IMU is working OK.

Thanks

**Comment by Richard-Gemmell** [comment]
Hi Savan,
I'm not sure what you want to know. Are you asking how to install the driver and run the examples?
cheers,
Richard

**Comment by savan8192** [comment]
Hi Richard,

Apologies for the very late reply. Yes, I was trying to install them in Pi but have figures out what I want to do now. Thanks again for your reply.

Cheers
Savan
