### ISSUE TITLE
Change SMBusWrapper to SMBus

### ISSUE THREAD

**Issue by BentPen** [Richard-Gemmell/lsm9ds1-rjg#2]
See 0.4.0 [here](https://github.com/kplindegaard/smbus2/blob/master/CHANGELOG.md).

Change needed in final import of lsm8ds1.py.

**Comment by BentPen** [comment]
Update: I made this issue by mistake. I had meant to post it on a derived repo ([here](https://github.com/thepaulm/lsm9ds1/blob/master/lsm9ds1/lsm9ds1.py)). Somehow I totally overlooked that I had wandered here to the parent repo it was forked from.

**Comment by Richard-Gemmell** [comment]
No problem. It's nice to know that someone's making use of it somewhere. :)

**Comment by BentPen** [comment]
Reopening because the issue actually is present here too! Albeit in i2c_transport.py in the case of this repo.

(I ended up returning to this repo hoping it would shed light on what I'm doing wrong with my Raspberry Pi 3B+ and this breakout board. Still stuck on that actually...)

**Comment by BentPen** [comment]
Okay, regarding my comment in parentheses above: It turns out I just wasn't thorough enough, and kept using GPIO 5/6 on my RPi (in keeping with how Adafruit did it in their MicroPython code). When I switched to GPIO 7/8 (the defaults for SPI0) the simple.py script ran flawlessly (though just a heads up, you spelled Gyro "Gryo" somewhere).

Now back to the tinkering! Thank you for your hard work on this code!

**Comment by Richard-Gemmell** [comment]
I've fixed the SMBus issue and the typos. I've released it as v1.0.0 in PyPi.

Thanks for reporting this.
